import React, { Fragment, useState, useEffect } from 'react';
// import { useSession } from 'next-auth/react';
import Head from 'next/head';
import Link from 'next/link';
import { ToastContainer } from 'react-toastify';

export default function DashboardScreen({ title, children }) {
  const [session, setSession] = useState();

  useEffect(() => {
    setSession(JSON.parse(sessionStorage.getItem('user')));
  }, []);
  return (
    <Fragment>
      {session?.isAdmin ? (
        <main>
          <Head>
            <title>{'Admin - Riere Farm'}</title>
            <meta name="description" content="Generated by create next app" />
            <link
              rel="icon"
              href="https://img.icons8.com/ios-filled/50/null/chicken.png"
            />
          </Head>
          <ToastContainer position="bottom-center" />

          <nav>
            <div className="w-full dark bg-black dark:bg-slate-800 md:bg-black-500 px-2 text-center fixed top-0 left-0 md:border-r-4 border-gray-600">
              <div className="md:relative">
                <ul className="list-reset flex flex-row  text-center ">
                  <li className="mr-3 flex-1">
                    <Link href="/admin/user">
                      <a className="block py-1 md:py-3 pl-1 align-middle text-gray-800 no-underline hover:text-pink-500 border-b-2 border-green-800 md:border-green-900 hover:border-green-500">
                        {' '}
                        <i className="fas fa-link pr-0 md:pr-3"></i>
                        <span
                          className={`pb-1 md:pb-0 text-xs  block md:inline-block ${
                            title == 'user' ? 'text-white' : 'text-gray-400'
                          }`}
                        >
                          User
                        </span>
                      </a>
                    </Link>
                  </li>
                  <li className="mr-3 flex-1">
                    <Link href="/admin/order">
                      <a className="block py-1 md:py-3 pl-1 align-middle text-gray-800 no-underline hover:text-white border-b-2 border-green-800 md:border-green-900 hover:border-green-500">
                        <i className="fas fa-link pr-0 md:pr-3"></i>
                        <span
                          className={`pb-1 md:pb-0 text-xs   block md:inline-block ${
                            title == 'order' ? 'text-white' : 'text-gray-400'
                          }`}
                        >
                          Order
                        </span>
                      </a>
                    </Link>
                  </li>
                  <li className="mr-3 flex-1">
                    <Link href="/admin/complete">
                      <a className="block py-1 md:py-3 pl-1 align-middle text-gray-800 no-underline  border-b-2 border-green-800 md:border-green-900 hover:border-green-50">
                        <i className="fas fa-link pr-0 md:pr-3 "></i>
                        <span
                          className={`pb-1 md:pb-0 text-xs  block md:inline-block  ${
                            title == 'complete'
                              ? 'text-white '
                              : 'text-gray-400'
                          }`}
                        >
                          Completed
                        </span>
                      </a>
                    </Link>
                  </li>
                </ul>
              </div>
            </div>
          </nav>

          <section>{children}</section>
        </main>
      ) : (
        <div className="text-red-600">Not allowed to view this page</div>
      )}
    </Fragment>
  );
}
